CREATE DATABASE ASSIGNMENT;
USE ASSIGNMENT;


CREATE TABLE AUTHOR(
             AUTHOR_ID INT PRIMARY KEY,
             FIRST_NAME VARCHAR(25),
             LAST_NAME VARCHAR(25),
             DATE_OF_BIRTH DATETIME,
             NATIONALITY VARCHAR(25)
);


CREATE TABLE BOOKS(
             BOOK_ID INT PRIMARY KEY,
             TITLE VARCHAR(25),
             AUTHOR_ID INT,
             PUBLICATION_YEAR YEAR,
             GENRE VARCHAR(25),
             ISBN VARCHAR(25),
             AVAILABLE_COPIES INT(10),
             FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHOR(AUTHOR_ID)
			 ON DELETE CASCADE
);


CREATE TABLE MEMBERS(
             MEMBER_ID INT PRIMARY KEY,
             FIRST_NAME VARCHAR(25),
             LAST_NAME VARCHAR(25),
             DATE_OF_BIRTH DATETIME,
             CONTACT_NUMBER VARCHAR(25),
             EMAIL VARCHAR(25),
             MEMBERSHIP_DATE DATETIME
);
DROP TABLE MEMBERS;


CREATE TABLE LOANS(
             LOAN_ID INT PRIMARY KEY,
             BOOK_ID INT,
             MEMBER_ID INT,
             LOAN_DATE DATETIME,
             RETURN_DATE DATETIME,
             ACTUAL_RETURN_DATE DATETIME,
             FOREIGN KEY (MEMBER_ID) REFERENCES MEMBERS(MEMBER_ID) ON DELETE CASCADE,
             FOREIGN KEY (BOOK_ID) REFERENCES BOOKS(BOOK_ID) ON DELETE CASCADE
);


CREATE TABLE STAFF(
             STAFF_ID INT PRIMARY KEY,
             FIRST_NAME VARCHAR(25),
             LAST_NAME VARCHAR(25),
             POSITION VARCHAR(25),
             CONTACT_NUMBER INT(10),
             EMAIL VARCHAR(25),
             HIRE_DATE DATETIME
);

